// Code generated by enum. DO NOT EDIT.
package test

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
)

// ErrInvalidColor is returned when an invalid value is provided for Color.
var ErrInvalidColor = errors.New("invalid Color")

// MustParseColor converts a string to a Color, and panics if is not valid.
func MustParseColor(value string) Color {
	val, err := ParseColor(value)
	if err != nil {
		panic(err)
	}
	return val
}

// ParseColor attempts to convert a string to a Color.
func ParseColor(value string) (Color, error) {
	switch strings.ToLower(value) {
	case "red":
		return ColorRed, nil
	case "green":
		return ColorGreen, nil
	case "blue":
		return ColorBlue, nil
	}

	return Color(""), fmt.Errorf(`%w %q; possible values: "red", "green", "blue"`, ErrInvalidColor, value)
}

// EnumValues identifies Color as an enum by returning a list of the possible values.
func (Color) EnumValues() []Color {
	return []Color{ColorRed, ColorGreen, ColorBlue}
}

// Type returns the type name of Color.
func (Color) Type() string {
	return "Color"
}

// EnumType returns the type name of Color.
func (Color) EnumType() string {
	return "Color"
}

// Set sets the value of the enum.
func (e *Color) Set(v string) error {
	var err error
	*e, err = ParseColor(v)
	return err
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values.
func (e Color) IsValid() bool {
	return e.Validate() == nil
}

// Validate checks if the typed value is  part of the allowed enumerated
// values. If not it returns an error.
func (e Color) Validate() error {
	switch string(e) {
	case "red":
		return nil
	case "green":
		return nil
	case "blue":
		return nil
	}

	return fmt.Errorf(`%w %q; possible values: "red", "green", "blue"`, ErrInvalidColor, e.String())
}

// String implements the Stringer interface.
func (e Color) String() string {
	return string(e)
}

// GoString implements the GoStringer interface.
func (e Color) GoString() string {
	switch string(e) {
	case "red":
		return `ColorRed("red")`
	case "green":
		return `ColorGreen("green")`
	case "blue":
		return `ColorBlue("blue")`
	}

	return ""
}

// MarshalText implements the text marshaller method.
func (e Color) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (e *Color) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseColor(name)
	if err != nil {
		return err
	}
	*e = tmp
	return nil
}

// ErrInvalidMode is returned when an invalid value is provided for Mode.
var ErrInvalidMode = errors.New("invalid Mode")

// EnumValues identifies Mode as an enum by returning a list of the possible values.
func (Mode) EnumValues() []Mode {
	return []Mode{ModeLight, ModeDark, ModeAuto}
}

// Type returns the type name of Mode.
func (Mode) Type() string {
	return "Mode"
}

// EnumType returns the type name of Mode.
func (Mode) EnumType() string {
	return "Mode"
}

// Set sets the value of the enum.
func (e *Mode) Set(v string) error {
	s, err := strconv.Atoi(v)
	if err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidMode, err)
	}
	newValue := Mode(s)
	if err := newValue.Validate(); err != nil {
		return err
	}
	*e = newValue
	return nil
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values.
func (e Mode) IsValid() bool {
	return e.Validate() == nil
}

// Validate checks if the typed value is  part of the allowed enumerated
// values. If not it returns an error.
func (e Mode) Validate() error {
	switch int(e) {
	case 0:
		return nil
	case 1:
		return nil
	case 2:
		return nil
	}

	return fmt.Errorf(`%w %q; possible values: 0, 1, 2`, ErrInvalidMode, e.String())
}

// String implements the Stringer interface.
func (e Mode) String() string {
	return strconv.Itoa(int(e))
}

// GoString implements the GoStringer interface.
func (e Mode) GoString() string {
	switch int(e) {
	case 0:
		return `ModeLight(0)`
	case 1:
		return `ModeDark(1)`
	case 2:
		return `ModeAuto(2)`
	}

	return ""
}

// MarshalText implements the text marshaller method.
func (e Mode) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (e *Mode) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseMode(name)
	if err != nil {
		return err
	}
	*e = tmp
	return nil
}
