package generator

import (
	"bytes"
	_ "embed"
	"fmt"
	"strings"
	"text/template"

	"github.com/Masterminds/sprig/v3"
	"golang.org/x/tools/imports"

	"github.com/marvinpeter95/enum/cmd/generator/parser"
)

//go:embed templates/enum.gotpl
var codeTemplateSource string

// Options defines the options for code generation.
type Options struct {
	CaseInsensitive    bool // CaseInsensitive indicates whether the generated parser should be case-insensitive.
	SkipTextMarshaling bool // SkipTextMarshaling indicates whether to skip generating MarshalText and UnmarshalText methods.
	SkipParser         bool // SkipParser indicates whether to skip generating the parser function.
}

// templateData defines the data structure passed to the code template.
type templateData struct {
	Enum    parser.Enum // Enum is the enum definition to be used in the template.
	Options Options     // Options are the code generation options to be used in the template.
}

// Process generates code for the given filename and types with the specified options.
func Process(filename string, types []string, options Options) ([]byte, error) {
	// Parse the input file to extract enum definitions.
	p, err := parser.Parse(filename, types)
	if err != nil {
		return nil, fmt.Errorf("failed to parse input file: %w", err)
	}

	// Print the parsed enums for debugging purposes.
	for _, enum := range p.Enums {
		fmt.Println(enum.String())
	}

	// Parse the code template.
	tpl, err := template.New("").Funcs(sprig.FuncMap()).Parse(codeTemplateSource)
	if err != nil {
		return nil, fmt.Errorf("failed to parse code template: %w", err)
	}

	var buf bytes.Buffer

	// Write the generated code header and package declaration.
	fmt.Fprintln(&buf, "// Code generated by enum. DO NOT EDIT.")
	fmt.Fprintf(&buf, "package %s\n", p.Package)

	// Generate code for each enum definition.
	for _, e := range p.Enums {
		td := templateData{Enum: *e, Options: options}

		// Check for existing MarshalText and UnmarshalText methods to avoid generating them if they already exist.
		if p.HasDeclaration(e.Name+".MarshalText") || p.HasDeclaration(e.Name+".UnmarshalText") {
			td.Options.SkipTextMarshaling = true
		}

		// Check for existing parser function to avoid generating it if it already exists.
		if p.HasDeclaration("Parse" + e.Name) {
			td.Options.SkipParser = true
		}

		// Execute the code template with the template data and write the generated code to the buffer.
		if err := tpl.Execute(&buf, &td); err != nil {
			return nil, fmt.Errorf("failed to execute code template: %w", err)
		}
	}

	// Format the generated code using go-imports to ensure proper formatting and import management.
	formatted, err := imports.Process("enum.go", buf.Bytes(), nil)
	if err != nil {
		// Print the unformatted code for debugging purposes if formatting fails.
		for i, line := range strings.Split(buf.String(), "\n") {
			fmt.Printf("%4d: %s\n", i+1, line)
		}
		err = fmt.Errorf("failed to format generated code: %w", err)
	}

	if err != nil {
		return nil, err
	}

	return formatted, nil
}
